alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring
    replicas: 2
    alertmanagerConfigMatcherStrategy:
      type: None
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi  # Persistent volume for Alertmanager

prometheus:
  prometheusSpec:
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi  # Persistent volume for Prometheus

grafana:
  persistence:
    enabled: true
    storageClassName: "standard"  # Use the correct storage class for Minikube, usually "standard"
    accessModes:
      - ReadWriteOnce
    size: 5Gi  # You can increase to 20Gi if needed
    finalizers:
      - kubernetes.io/pvc-protection

  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  initChownData:
    enabled: false
